"""
Django settings for yellowant_agile_CRM project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import json
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
data = open('yellowant_app_credentials.json').read()
data_json = json.loads(data)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#-------------------------------------------------------------------------------------

app_name = os.environ.get("HEROKU_APP_NAME")
BASE_URL = "https://{}.herokuapp.com".format(app_name)
ALLOWED_HOSTS = ['*', '{}.herokuapp.com'.format(app_name)]


#-------------------------------------------------------------------------------------


### YellowAnt specific settings ###
# URL to obtain oauth2 access for a YA user
YA_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
# URL to receive oauth2 codes from YA for user authentication. As a developer, you need to provide this URL in the YA
# developer console so that YA knows exactly where to send the oauth2 codes.
YA_REDIRECT_URL = BASE_URL+"/redirecturl/" #"http://45c9c08e.ngrok.io/redirecturl/"

# Numerical ID generated when you register your application through the YA developer console
BASE_HREF="/"
SITE_PROTOCOL = "https://"



YA_APP_ID = str(data_json['application_id'])
# Client ID generated from the YA developer console. Required to identify requests from this application to YA
YA_CLIENT_ID = str(data_json['client_id'])
# Client secret generated from the YA developer console. Required to identify requests from this application to YA
YA_CLIENT_SECRET = str(data_json['client_secret'])
# Verification token generated from the YA developer console. This application can verify requests from YA as they will
# carry the verification token
YA_VERIFICATION_TOKEN = str(data_json['verification_token'])
#YA_VERIFICATION_TOKEN = os.environ.get("YA_VERIFICATION_TOKEN", "flezxPkJQXNPnBhoSsRTPZjBrc0t5pHxklftUgDwJinLHQNE4fuB8bvpKZYarGj08pavza1I4Z8Hp0vznFwkDlSCwI8SWW7obI9TzduZZYKINkT5OQrzhlgyZwbyn7Kb")

### END YellowAnt specific settings ###


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#x9q+c*t9$=buk$i@m&6e+k@m(q@uds0gd=9=3cej6u#_u=m*%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True







# SECURITY WARNING: remove wildcard condition from ALLOWED_HOSTS
ALLOWED_HOSTS = ["*", '{}.herokuapp.com'.format(app_name)]



#---------------------------------------------------------------------------------

DEV_ENV = os.environ.get('ENV', 'DEV')
if DEV_ENV == "DEV":
    BASE_URL = "https://dd272eb3.ngrok.io"
    SITE_DOMAIN_URL = "ngrok.io"
elif DEV_ENV == "HEROKU":
    BASE_URL = "https://{}.herokuapp.com/".format(app_name)
    app_name = os.environ.get("HEROKU_APP_NAME")
    SITE_DOMAIN_URL = "herokuapp.com"
#----------------------------------------------------------------------------------
# Application definition

INSTALLED_APPS = [
    'lib.yellowant_api',
    'lib.web',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yellowant_agile_CRM.urls'
CORS_ORIGIN_ALLOW_ALL = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yellowant_agile_CRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_db',
        'USER':'root',
        'PASSWORD':'abhiawesome007',
        'PORT':'',
    }
}

#-------------------------------------------------------------------

if DEV_ENV == "HEROKU":
    import dj_database_url
    db_from_env = dj_database_url.config()
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['CONN_MAX_AGE'] = 500
#--------------------------------------------------------------------


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')